/* Pursuits dashboard — multiple D3 collapsible trees on one zoomable canvas.
   Data: window.TREES (generated by build.js from the wiki under pursuits/).
   Each node has a doc icon (open the wiki doc) and, in server mode, a + to add a child note. */
'use strict';
(function () {
  const PALETTE = ['var(--c0)', 'var(--c1)', 'var(--c2)', 'var(--c3)', 'var(--c4)', 'var(--c5)'];
  const TREE_COLORS = ['var(--c0)', 'var(--c2)', 'var(--c3)', 'var(--c5)'];

  const dy = 280, GAP = 90, MARGIN_L = 60, ROW_GAP = 34;
  const baseH = d => (d.depth === 0 ? 32 : 28);
  // effective scale = product of own + ancestor scales (so a node sizes itself AND its subtree)
  const eComp = root => root.eachBefore(d => { d.escale = (d.parent ? d.parent.escale : 1) * (d.scale || 1); });
  const rowSlot = d => baseH(d) * (d.escale || 1) + ROW_GAP;
  const tree = d3.tree().nodeSize([1, dy]).separation((a, b) => (rowSlot(a) + rowSlot(b)) / 2);
  const diagonal = d3.linkHorizontal().x(d => d.hx).y(d => d.vy);

  const svg = d3.select('svg');
  const canvas = svg.append('g');
  const zoom = d3.zoom().scaleExtent([0.25, 2.5]).on('zoom', e => canvas.attr('transform', e.transform));
  svg.call(zoom);

  const MAXW = 230;
  const rawW = s => s.length * 7.2 + 64;            // +room for the doc icon
  const nodeW = (s, root) => root ? rawW(s) : Math.min(rawW(s), MAXW);
  const maxChars = Math.floor((MAXW - 64) / 7.2);
  const fitText = (s, root) => (!root && s.length > maxChars) ? s.slice(0, maxChars - 1) + '…' : s;
  const collapsed = d => !!(d._children && !d.children);
  const colorOf = d => d.depth === 0 ? TREE_COLORS[d.ti % TREE_COLORS.length] : PALETTE[(d.branch >= 0 ? d.branch : 0) % PALETTE.length];
  const repoRel = url => (url || '').replace(/^(\.\.\/)+/, '');
  const keyOf = d => d.data.id || d.data.url;  // stable view-state key (survives path changes)

  let SERVER = false;
  let states = [];
  let uid = 0;
  // per-node size, persisted by doc url (survives reloads; no disk writes)
  let SCALES = {};
  try { SCALES = JSON.parse(localStorage.getItem('pursuits-scales') || '{}'); } catch (e) {}
  function saveScales() { try { localStorage.setItem('pursuits-scales', JSON.stringify(SCALES)); } catch (e) {} }
  // per-node manual drag offset (applies to the node + its subtree), persisted by doc url
  let OFFSETS = {};
  try { OFFSETS = JSON.parse(localStorage.getItem('pursuits-offsets') || '{}'); } catch (e) {}
  function saveOffsets() { try { localStorage.setItem('pursuits-offsets', JSON.stringify(OFFSETS)); } catch (e) {} }
  // per-node highlight flag (halo + fill with the node color instead of white), persisted by doc url
  let HILITES = {};
  try { HILITES = JSON.parse(localStorage.getItem('pursuits-hilites') || '{}'); } catch (e) {}
  function saveHilites() { try { localStorage.setItem('pursuits-hilites', JSON.stringify(HILITES)); } catch (e) {} }
  // cumulative offset down the tree → render coords (hx,vy) = layout (y,x) + inherited offset
  function computePos(root) {
    root.eachBefore(d => {
      d.cox = (d.parent ? d.parent.cox : 0) + (d.ox || 0);
      d.coy = (d.parent ? d.parent.coy : 0) + (d.oy || 0);
      d.hx = d.y + d.cox;
      d.vy = d.x + d.coy;
    });
  }

  function buildStates(TREES) {
    canvas.selectAll('*').remove();
    states = []; uid = 0;
    let dirtyS = false, dirtyO = false, dirtyH = false;
    TREES.forEach((data, ti) => {
      const root = d3.hierarchy(data);
      root.hx0 = 0; root.vy0 = 0;
      root.descendants().forEach(d => {
        d.id = uid++; d._children = d.children; d.ti = ti;
        const k = keyOf(d), ou = d.data.url;
        // size — migrate any legacy url-keyed value onto the stable id
        let sc = SCALES[k];
        if (sc === undefined && k !== ou && SCALES[ou] !== undefined) { sc = SCALES[ou]; SCALES[k] = sc; delete SCALES[ou]; dirtyS = true; }
        d.scale = sc;
        // position offset — same migration
        let of = OFFSETS[k];
        if (!of && k !== ou && OFFSETS[ou]) { of = OFFSETS[ou]; OFFSETS[k] = of; delete OFFSETS[ou]; dirtyO = true; }
        d.ox = of ? of.x : 0; d.oy = of ? of.y : 0;
        // highlight flag — same migration
        let hl = HILITES[k];
        if (hl === undefined && k !== ou && HILITES[ou] !== undefined) { hl = HILITES[ou]; HILITES[k] = hl; delete HILITES[ou]; dirtyH = true; }
        d.hl = !!hl;
        let a = d; while (a.depth > 1) a = a.parent;
        d.branch = a.depth === 0 ? -1 : a.parent.children.indexOf(a);
      });
      root.descendants().forEach(d => { if (d.depth >= 2 && d.children) { d._children = d.children; d.children = null; } });
      const g = canvas.append('g').attr('class', 'tree');
      states.push({ data, root, g, gLink: g.append('g'), gNode: g.append('g'), ti, yOffset: 0 });
    });
    if (dirtyS) saveScales();
    if (dirtyO) saveOffsets();
    if (dirtyH) saveHilites();
  }

  function layout() {
    let offset = 0;
    states.forEach(s => {
      eComp(s.root);
      tree(s.root);
      computePos(s.root);
      let minX = Infinity, maxX = -Infinity;
      s.root.each(d => { minX = Math.min(minX, d.vy); maxX = Math.max(maxX, d.vy); });
      s.yOffset = offset - minX;
      offset += (maxX - minX) + GAP;
    });
  }

  // drag a node → move it + its subtree (offset cascades to descendants); empty-space drag still pans
  const drag = d3.drag().clickDistance(5)
    .on('start', function (event, d) {
      event.sourceEvent.stopPropagation();
      const p = d3.pointer(event, canvas.node());
      d._p0 = p; d._ox0 = d.ox || 0; d._oy0 = d.oy || 0;
    })
    .on('drag', function (event, d) {
      const p = d3.pointer(event, canvas.node());
      d.ox = d._ox0 + (p[0] - d._p0[0]);
      d.oy = d._oy0 + (p[1] - d._p0[1]);
      drawTree(states[d.ti]);
    })
    .on('end', function (event, d) {
      OFFSETS[keyOf(d)] = { x: d.ox || 0, y: d.oy || 0 };
      saveOffsets();
    });

  // instant (no-transition) reposition of one tree — used during drag
  function drawTree(s) {
    computePos(s.root);
    s.gNode.selectAll('g.node').attr('transform', d => 'translate(' + d.hx + ',' + d.vy + ') scale(' + (d.escale || 1) + ')');
    s.gLink.selectAll('path').attr('d', diagonal);
  }

  function docGlyph(sel) {
    sel.append('path').attr('d', 'M-3.2,-5 H1.4 L3.4,-3 V5 H-3.2 Z').attr('fill', '#fff');
    sel.append('path').attr('d', 'M1.4,-5 V-3 H3.4').attr('fill', 'none').attr('stroke', colorOf).attr('stroke-width', 0.9);
    sel.append('path').attr('d', 'M-1.6,-0.6 H1.6 M-1.6,1.8 H1.6').attr('stroke', colorOf).attr('stroke-width', 0.9).attr('stroke-linecap', 'round');
  }

  function renderTree(s, src) {
    const t = svg.transition().duration(320);
    const nodes = s.root.descendants().reverse();
    const links = s.root.links();

    const node = s.gNode.selectAll('g.node').data(nodes, d => keyOf(d) || d.id);
    const nodeEnter = node.enter().append('g').attr('class', 'node')
      .attr('transform', d => 'translate(' + (d.hx0 !== undefined ? d.hx0 : src.hx0) + ',' + (d.vy0 !== undefined ? d.vy0 : src.vy0) + ')')
      .attr('fill-opacity', 0).attr('stroke-opacity', 0)
      .on('click', (e, d) => {
        const hasKids = d.children || d._children;
        if (!hasKids) { openDoc(d); return; }
        d.children = d.children ? null : d._children; refresh(d);
      })
      .call(drag);

    const W = d => nodeW(d.data.name, d.depth === 0);

    nodeEnter.append('rect')
      .attr('height', d => d.depth === 0 ? 32 : 28).attr('y', d => d.depth === 0 ? -16 : -14)
      .attr('rx', 13).attr('ry', 13)
      .attr('x', d => -W(d) / 2).attr('width', W)
      .attr('fill', 'var(--card)').attr('stroke', colorOf).attr('stroke-width', d => d.depth === 0 ? 2.4 : 1.6);

    nodeEnter.append('circle').attr('r', 4).attr('cx', d => -W(d) / 2).attr('fill', colorOf);

    nodeEnter.append('text').attr('class', d => 'label' + (d.depth === 0 ? ' root' : ''))
      .attr('text-anchor', 'start').attr('dy', '0.32em')
      .attr('x', d => -W(d) / 2 + 14)
      .text(d => fitText(d.data.name, d.depth === 0))
      .append('title').text(d => d.data.name);

    // doc icon (always) — open the wiki doc
    const doc = nodeEnter.append('g').attr('class', 'docbtn')
      .attr('transform', d => 'translate(' + (W(d) / 2 - 2) + ',0)')
      .on('click', (e, d) => { e.stopPropagation(); openDoc(d); });
    doc.append('title').text('Open doc');
    doc.append('circle').attr('r', 9).attr('fill', colorOf);
    doc.each(function () { docGlyph(d3.select(this)); });

    // settings (gear) icon — above the doc icon — opens the size dialog
    const gear = nodeEnter.append('g').attr('class', 'gearbtn')
      .attr('transform', d => 'translate(' + (W(d) / 2 - 2) + ',-18)')
      .on('click', (e, d) => { e.stopPropagation(); openNodeInfo(e, d); });
    gear.append('title').text('Node info');
    gear.append('circle').attr('r', 9).attr('fill', colorOf);
    gear.append('text').attr('text-anchor', 'middle').attr('dy', '0.32em').attr('font-size', 11).attr('fill', '#fff').text('⚙');

    // count badge (collapsed) — outside right
    const badge = nodeEnter.append('g').attr('class', 'badge')
      .attr('transform', d => 'translate(' + (W(d) / 2 + 20) + ',0)');
    badge.append('circle').attr('r', 9).attr('fill', colorOf);
    badge.append('text').attr('class', 'count').attr('text-anchor', 'middle').attr('dy', '0.32em');

    // add button (hover, server mode) — below the doc icon
    const add = nodeEnter.append('g').attr('class', 'addbtn')
      .attr('transform', d => 'translate(' + (W(d) / 2 - 2) + ',18)')
      .on('click', (e, d) => { e.stopPropagation(); openAddModal(d); });
    add.append('title').text('Add note here');
    add.append('circle').attr('r', 9).attr('fill', colorOf);
    add.append('path').attr('d', 'M0,-4 V4 M-4,0 H4').attr('stroke', '#fff').attr('stroke-width', 2).attr('stroke-linecap', 'round');

    const merged = node.merge(nodeEnter);
    merged.select('.badge').style('display', d => collapsed(d) ? null : 'none');
    merged.select('.badge .count').text(d => collapsed(d) ? d._children.length : '');
    // highlight: halo (CSS via .hl + --halo) + fill the rect with the node color, white label for contrast
    merged.classed('hl', d => !!d.hl).style('--halo', d => d.hl ? colorOf(d) : null);
    merged.select('rect').attr('fill', d => d.hl ? colorOf(d) : 'var(--card)');
    merged.select('text.label').attr('fill', d => d.hl ? '#fff' : null);
    merged.transition(t)
      .attr('transform', d => 'translate(' + d.hx + ',' + d.vy + ') scale(' + (d.escale || 1) + ')')
      .attr('fill-opacity', 1).attr('stroke-opacity', 1);

    node.exit().transition(t).remove()
      .attr('transform', 'translate(' + src.hx + ',' + src.vy + ')')
      .attr('fill-opacity', 0).attr('stroke-opacity', 0);

    const link = s.gLink.selectAll('path').data(links, d => keyOf(d.target) || d.target.id);
    const linkEnter = link.enter().append('path').attr('class', 'link')
      .attr('stroke', d => colorOf(d.target))
      .attr('d', () => { const o = { hx: src.hx0, vy: src.vy0 }; return diagonal({ source: o, target: o }); });
    link.merge(linkEnter).transition(t).attr('d', diagonal).attr('stroke', d => colorOf(d.target));
    link.exit().transition(t).remove()
      .attr('d', () => { const o = { hx: src.hx, vy: src.vy }; return diagonal({ source: o, target: o }); });

    s.root.eachBefore(d => { d.hx0 = d.hx; d.vy0 = d.vy; });
  }

  function stableRebuild(newTrees) {
    const snap = {}, oldYOffsets = states.map(s => s.yOffset);
    states.forEach(s => s.root.each(d => { const k = keyOf(d); if (k) snap[k] = { hx: d.hx, vy: d.vy }; }));
    window.TREES = newTrees;
    buildStates(newTrees);
    layout();  // sets d.x/d.y for new nodes; also clobbers s.yOffset — we restore below
    let dirty = false;
    states.forEach((s, i) => {
      if (oldYOffsets[i] !== undefined) s.yOffset = oldYOffsets[i];
      s.root.eachBefore(d => {
        const k = keyOf(d), pcox = d.parent ? d.parent.cox : 0, pcoy = d.parent ? d.parent.coy : 0;
        if (k && snap[k]) {
          d.ox = snap[k].hx - d.y - pcox; d.oy = snap[k].vy - d.x - pcoy;
          OFFSETS[k] = { x: d.ox, y: d.oy }; dirty = true;
        } else {
          d.hx0 = d.parent ? d.parent.hx : 0; d.vy0 = d.parent ? d.parent.vy : 0;
        }
        d.cox = pcox + (d.ox || 0); d.coy = pcoy + (d.oy || 0);
        d.hx = d.y + d.cox; d.vy = d.x + d.coy;
      });
      s.g.attr('transform', 'translate(' + MARGIN_L + ',' + s.yOffset + ')');
      renderTree(s, s.root);
    });
    if (dirty) saveOffsets();
    if (!document.getElementById('nodeinfo').hidden && niKey) {   // keep an open panel bound to the live (rebuilt) node; don't clobber an in-progress edit
      const d = niResolve(niKey);
      if (!d) closeSizePop();
      else { infoNode = d; sizeNode = d; const ae = document.activeElement; if (!(ae && ae.closest && ae.closest('#nodeinfo'))) buildNodeInfo(d); }
    }
  }

  function refresh(source) {
    layout();
    states.forEach(s => {
      const src = (source && source.ti === s.ti) ? source : s.root;
      s.g.transition().duration(320).attr('transform', 'translate(' + MARGIN_L + ',' + s.yOffset + ')');
      renderTree(s, src);
    });
  }

  function fit() {
    layout();
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    states.forEach(s => s.root.each(d => {
      const X = MARGIN_L + d.hx, Y = s.yOffset + d.vy;
      minX = Math.min(minX, X); maxX = Math.max(maxX, X);
      minY = Math.min(minY, Y); maxY = Math.max(maxY, Y);
    }));
    const w = window.innerWidth, h = window.innerHeight;
    const tw = (maxX - minX) + 420, th = (maxY - minY) + 160;
    const k = Math.min(1.4, Math.min(w / tw, h / th));
    const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2;
    svg.transition().duration(440).call(zoom.transform,
      d3.zoomIdentity.translate(w / 2 - k * cx, h / 2 - k * cy).scale(k));
  }

  function openDoc(d) {
    if (SERVER) openEditor(d);
    else if (d.data.url) window.open(d.data.url, '_blank'); // static mode: read-only view
  }

  // ---- inline doc editor ----
  let edNode = null, edPath = null;
  async function openEditor(d) {
    edNode = d; edPath = repoRel(d.data.url);
    document.getElementById('ed-title').textContent = d.data.name;
    document.getElementById('ed-path').textContent = edPath;
    document.getElementById('ed-msg').textContent = 'Loading…';
    document.getElementById('ed-text').value = '';
    document.getElementById('editor').hidden = false;
    try {
      const r = await fetch('/api/doc?path=' + encodeURIComponent(edPath));
      const j = await r.json();
      if (!j.ok) { document.getElementById('ed-msg').textContent = 'Error: ' + j.error; return; }
      document.getElementById('ed-text').value = j.content;
      document.getElementById('ed-msg').textContent = '';
    } catch (e) { document.getElementById('ed-msg').textContent = 'Error: ' + e.message; }
  }
  function closeEditor() { document.getElementById('editor').hidden = true; edNode = null; edPath = null; }
  async function saveDoc() {
    const content = document.getElementById('ed-text').value;
    const msg = document.getElementById('ed-msg');
    msg.textContent = 'Saving…';
    try {
      const r = await fetch('/api/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: edPath, content }) });
      const j = await r.json();
      if (!j.ok) { msg.textContent = 'Error: ' + j.error; return; }
      msg.textContent = 'Saved ✓';
      if (j.title && edNode && j.title !== edNode.data.name) {  // title changed → relabel tree
        stableRebuild(j.trees);
        document.getElementById('ed-title').textContent = j.title;
      }
    } catch (e) { msg.textContent = 'Error: ' + e.message; }
  }

  // ---- add-note modal ----
  let addParent = null; // d3 node, or null = root
  function openAddModal(d) {
    addParent = d;
    const ctx = d ? ('Adds a note under “' + d.data.name + '”') : 'Adds a new top-level pursuit';
    document.getElementById('modal-ctx').textContent = ctx;
    document.getElementById('note-title').value = '';
    document.getElementById('note-body').value = '';
    document.getElementById('note-msg').textContent = SERVER ? '' : 'Run via: node dashboard/serve.js — file mode can\'t write.';
    document.getElementById('modal').hidden = false;
    document.getElementById('note-title').focus();
  }
  function closeModal() { document.getElementById('modal').hidden = true; }
  async function submitAdd() {
    const title = document.getElementById('note-title').value.trim();
    const note = document.getElementById('note-body').value;
    const msg = document.getElementById('note-msg');
    if (!title) { msg.textContent = 'Title required.'; return; }
    if (!SERVER) { msg.textContent = 'Server not running — start: node dashboard/serve.js'; return; }
    msg.textContent = 'Adding…';
    try {
      const parent = addParent ? repoRel(addParent.data.url) : 'root';
      const r = await fetch('/api/add', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parent, title, note }) });
      const j = await r.json();
      if (!j.ok) { msg.textContent = 'Error: ' + j.error; return; }
      stableRebuild(j.trees);
      closeModal();
    } catch (e) { msg.textContent = 'Error: ' + e.message; }
  }

  // ---- per-node info panel: status · tags · summary · connections + size/highlight/rename/archive ----
  let sizeNode = null;                                  // kept name — nudgeScale/toggleHilite/renameNode/archiveNode operate on it
  let infoNode = null, niKey = null, niFocusTag = false;
  const NI_STATUS = { note: { label: 'Note', color: 'var(--muted)' }, active: { label: 'Active', color: 'var(--c2)' }, blocked: { label: 'Blocked', color: 'var(--c4)' }, done: { label: 'Done', color: 'var(--c0)' } };
  function niEl(tag, cls) { const el = document.createElement(tag); if (cls) el.className = cls; return el; }
  function openNodeInfo(e, d) { sizeNode = d; infoNode = d; niKey = keyOf(d); buildNodeInfo(d); document.getElementById('nodeinfo').hidden = false; }
  function closeSizePop() { document.getElementById('nodeinfo').hidden = true; sizeNode = null; infoNode = null; niKey = null; }   // name kept: existing callers (renameNode/archiveNode/Escape) reuse it
  async function saveNodeMeta(patch) {
    if (!SERVER || !infoNode) return;
    try { await fetch('/api/node-meta', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.assign({ path: repoRel(infoNode.data.url) }, patch)) }); }
    catch (_) {}   // the SSE broadcast refreshes the tree; the panel was already updated optimistically
  }
  function centerOnNode(d) {
    const s = states[d.ti]; if (!s || d.hx === undefined) return;
    const X = MARGIN_L + d.hx, Y = s.yOffset + d.vy, k = d3.zoomTransform(svg.node()).k || 1;
    svg.transition().duration(420).call(zoom.transform, d3.zoomIdentity.translate(window.innerWidth / 2 - k * X, window.innerHeight / 2 - k * Y).scale(k));
  }
  function niResolve(key) { let found = null; states.forEach(s => s.root.each(d => { if (keyOf(d) === key) found = d; })); return found; }
  function niGoto(targetKey) {
    let t = niResolve(targetKey), a = t && t.parent, need = false;   // expand ancestors so a collapsed target lays out + shows
    while (a) { if (a._children && !a.children) { a.children = a._children; need = true; } a = a.parent; }
    const go = () => { const d = niResolve(targetKey); if (!d) return; openNodeInfo(null, d); centerOnNode(d); };
    if (need && t) { refresh(t.parent || t); setTimeout(go, 40); } else go();
  }
  function niConnSection(title, nodes) {
    const wrap = niEl('div'); const h = niEl('div', 'ni-sec-lbl'); h.textContent = title; wrap.appendChild(h);
    nodes.forEach(n => {
      const row = niEl('div', 'ni-connrow'); row.title = 'Go to "' + n.data.name + '"';
      const dot = niEl('span', 'ni-conndot'); dot.style.background = colorOf(n); row.appendChild(dot);
      const nm = niEl('span', 'ni-connname'); nm.textContent = n.data.name; row.appendChild(nm);
      const kc = (n.children || n._children || []).length; if (kc) { const c = niEl('span', 'ni-connkind'); c.textContent = kc; row.appendChild(c); }
      row.onclick = () => niGoto(keyOf(n));
      wrap.appendChild(row);
    });
    return wrap;
  }
  function buildNodeInfo(d) {
    document.getElementById('ni-name').textContent = d.data.name;
    document.getElementById('ni-glyph').style.background = colorOf(d);
    // status pills (server) or a read-only pill
    const sbox = document.getElementById('ni-status'); sbox.innerHTML = '';
    if (SERVER) {
      Object.keys(NI_STATUS).forEach(s => {
        const b = niEl('button', 'ni-status' + (d.data.status === s ? ' on' : '')); b.textContent = NI_STATUS[s].label;
        if (d.data.status === s) b.style.background = NI_STATUS[s].color;
        b.onclick = () => { const nv = d.data.status === s ? null : s; d.data.status = nv || undefined; saveNodeMeta({ status: nv || '' }); buildNodeInfo(d); };
        sbox.appendChild(b);
      });
    } else if (d.data.status) {
      const meta = NI_STATUS[d.data.status] || { label: d.data.status, color: 'var(--muted)' };
      const pill = niEl('span', 'ni-status on'); pill.textContent = meta.label; pill.style.background = meta.color; sbox.appendChild(pill);
    }
    // summary (save on blur)
    const ta = document.getElementById('ni-summary'); ta.value = d.data.summary || ''; ta.readOnly = !SERVER;
    ta.onblur = SERVER ? () => { const v = ta.value.trim(); if ((d.data.summary || '') !== v) { d.data.summary = v || undefined; saveNodeMeta({ summary: v }); } } : null;
    // tags (chips + add)
    const tbox = document.getElementById('ni-tags'); tbox.innerHTML = '';
    (d.data.tags || []).forEach(tg => {
      const chip = niEl('span', 'ni-tag'); chip.appendChild(document.createTextNode(tg));
      if (SERVER) { const x = niEl('b'); x.textContent = '×'; x.title = 'Remove'; x.onclick = () => { d.data.tags = (d.data.tags || []).filter(z => z !== tg); saveNodeMeta({ tags: d.data.tags }); buildNodeInfo(d); }; chip.appendChild(x); }
      tbox.appendChild(chip);
    });
    if (SERVER) {
      const inp = niEl('input', 'ni-taginput ni-edit'); inp.placeholder = '+ tag'; inp.autocomplete = 'off'; inp.spellcheck = false;
      inp.onkeydown = ev => { if (ev.key === 'Enter') { ev.preventDefault(); const v = inp.value.trim().toLowerCase().replace(/,/g, ''); if (!v) return; d.data.tags = [...(d.data.tags || []), v].filter((z, i, arr) => arr.indexOf(z) === i); saveNodeMeta({ tags: d.data.tags }); niFocusTag = true; buildNodeInfo(d); } else if (ev.key === 'Escape') inp.blur(); };
      tbox.appendChild(inp);
    }
    if (niFocusTag) { niFocusTag = false; const ti = tbox.querySelector('.ni-taginput'); if (ti) ti.focus(); }
    // connections — parent + children (the tree's edges)
    const nav = document.getElementById('ni-nav'); nav.innerHTML = '';
    const kids = d.children || d._children || [];
    if (d.parent) nav.appendChild(niConnSection('Parent', [d.parent]));
    if (kids.length) nav.appendChild(niConnSection('Children', kids));
    // existing controls
    document.getElementById('size-val').textContent = Math.round((d.scale || 1) * 100) + '%';
    updateHlBtn();
  }
  async function renameNode() {
    if (!sizeNode || !SERVER) return;
    const cur = sizeNode.data.name;
    const next = prompt('Rename node (also renames the doc file + updates backlinks):', cur);
    if (next === null) return;
    const title = next.trim();
    if (!title || title === cur) { closeSizePop(); return; }
    const rel = repoRel(sizeNode.data.url);
    closeSizePop();
    try {
      const r = await fetch('/api/rename', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: rel, title }) });
      const j = await r.json();
      if (!j.ok) { alert('Rename failed: ' + j.error); return; }
      stableRebuild(j.trees);
    } catch (e) { alert('Rename error: ' + e.message); }
  }
  async function archiveNode() {
    if (!sizeNode || !SERVER) return;
    const name = sizeNode.data.name;
    if (!confirm('Archive "' + name + '"?\n\nThe file moves to pursuits/.archive/ and disappears from the dashboard.')) return;
    const rel = repoRel(sizeNode.data.url);
    closeSizePop();
    try {
      const r = await fetch('/api/archive', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: rel }) });
      const j = await r.json();
      if (!j.ok) { alert('Archive failed: ' + j.error); return; }
      stableRebuild(j.trees);
    } catch (e) { alert('Archive error: ' + e.message); }
  }
  function updateHlBtn() {
    const b = document.getElementById('size-hl');
    if (!b || !sizeNode) return;
    b.classList.toggle('on', !!sizeNode.hl);
    b.textContent = sizeNode.hl ? '✓ Highlighted' : 'Highlight';
  }
  function toggleHilite() {
    if (!sizeNode) return;
    sizeNode.hl = !sizeNode.hl;
    const k = keyOf(sizeNode);
    if (sizeNode.hl) HILITES[k] = true; else delete HILITES[k];
    saveHilites();
    updateHlBtn();
    refresh(sizeNode);
  }
  function nudgeScale(dir) {
    if (!sizeNode) return;
    sizeNode.scale = Math.max(0.4, Math.min(2.5, (sizeNode.scale || 1) * (dir > 0 ? 1.15 : 1 / 1.15)));
    SCALES[keyOf(sizeNode)] = sizeNode.scale; saveScales();
    document.getElementById('size-val').textContent = Math.round(sizeNode.scale * 100) + '%';
    refresh(sizeNode);
  }

  d3.select('#expand').on('click', () => { states.forEach(s => s.root.each(d => { if (d._children) d.children = d._children; })); refresh(null); setTimeout(fit, 360); });
  d3.select('#collapse').on('click', () => { states.forEach(s => s.root.descendants().forEach(d => { if (d.depth >= 1 && d.children) { d._children = d.children; d.children = null; } })); refresh(null); setTimeout(fit, 360); });
  d3.select('#fit').on('click', fit);
  d3.select('#addnote').on('click', () => openAddModal(null));
  document.getElementById('note-cancel').onclick = closeModal;
  document.getElementById('note-save').onclick = submitAdd;
  document.getElementById('modal').addEventListener('click', e => { if (e.target.id === 'modal') closeModal(); });
  document.getElementById('ed-close').onclick = closeEditor;
  document.getElementById('ed-save').onclick = saveDoc;
  document.getElementById('ed-openext').onclick = () => { if (edPath) fetch('/api/open?path=' + encodeURIComponent(edPath)).catch(() => {}); };
  document.getElementById('size-up').onclick = () => nudgeScale(1);
  document.getElementById('size-down').onclick = () => nudgeScale(-1);
  document.getElementById('size-hl').onclick = toggleHilite;
  document.getElementById('size-rename').onclick = renameNode;
  document.getElementById('size-archive').onclick = archiveNode;
  document.getElementById('ni-close').onclick = closeSizePop;
  document.getElementById('ni-notes').onclick = () => { const d = infoNode; closeSizePop(); if (d) openEditor(d); };
  document.addEventListener('click', e => { const pop = document.getElementById('nodeinfo'); if (!pop.hidden && !pop.contains(e.target) && !e.target.closest('.gearbtn')) closeSizePop(); });
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') { closeModal(); closeEditor(); closeSizePop(); }
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 's' && !document.getElementById('editor').hidden) { e.preventDefault(); saveDoc(); }
  });
  window.addEventListener('resize', fit);

  // detect server mode, then render
  fetch('/api/ping').then(r => r.ok).then(ok => {
    SERVER = !!ok;
    if (SERVER) {
      const es = new EventSource('/api/events');
      es.onmessage = e => { try { stableRebuild(JSON.parse(e.data)); } catch (_) {} };
    }
  }).catch(() => { SERVER = false; })
    .finally(() => { document.body.classList.toggle('server', SERVER); document.body.classList.add('checked'); });
  buildStates(window.TREES);
  refresh(null);
  setTimeout(fit, 60);
})();
