/* Pursuits dashboard — multiple D3 collapsible trees on one zoomable canvas.
   Data: window.TREES (generated by build.js from the wiki under pursuits/).
   Each node has a doc icon (open the wiki doc) and, in server mode, a + to add a child note. */
'use strict';
(function () {
  const PALETTE = ['var(--c0)', 'var(--c1)', 'var(--c2)', 'var(--c3)', 'var(--c4)', 'var(--c5)'];
  const TREE_COLORS = ['var(--c0)', 'var(--c2)', 'var(--c3)', 'var(--c5)'];

  const dx = 36, dy = 260, GAP = 80, MARGIN_L = 60;
  const tree = d3.tree().nodeSize([dx, dy]);
  const diagonal = d3.linkHorizontal().x(d => d.y).y(d => d.x);

  const svg = d3.select('svg');
  const canvas = svg.append('g');
  const zoom = d3.zoom().scaleExtent([0.25, 2.5]).on('zoom', e => canvas.attr('transform', e.transform));
  svg.call(zoom);

  const MAXW = 230;
  const rawW = s => s.length * 7.2 + 64;            // +room for the doc icon
  const nodeW = (s, root) => root ? rawW(s) : Math.min(rawW(s), MAXW);
  const maxChars = Math.floor((MAXW - 64) / 7.2);
  const fitText = (s, root) => (!root && s.length > maxChars) ? s.slice(0, maxChars - 1) + '…' : s;
  const collapsed = d => !!(d._children && !d.children);
  const colorOf = d => d.depth === 0 ? TREE_COLORS[d.ti % TREE_COLORS.length] : PALETTE[(d.branch >= 0 ? d.branch : 0) % PALETTE.length];
  const repoRel = url => (url || '').replace(/^(\.\.\/)+/, '');

  let SERVER = false;
  let states = [];
  let uid = 0;

  function buildStates(TREES) {
    canvas.selectAll('*').remove();
    states = []; uid = 0;
    TREES.forEach((data, ti) => {
      const root = d3.hierarchy(data);
      root.x0 = 0; root.y0 = 0;
      root.descendants().forEach(d => {
        d.id = uid++; d._children = d.children; d.ti = ti;
        let a = d; while (a.depth > 1) a = a.parent;
        d.branch = a.depth === 0 ? -1 : a.parent.children.indexOf(a);
      });
      root.descendants().forEach(d => { if (d.depth >= 2 && d.children) { d._children = d.children; d.children = null; } });
      const g = canvas.append('g').attr('class', 'tree');
      states.push({ data, root, g, gLink: g.append('g'), gNode: g.append('g'), ti, yOffset: 0 });
    });
  }

  function layout() {
    let offset = 0;
    states.forEach(s => {
      tree(s.root);
      let minX = Infinity, maxX = -Infinity;
      s.root.each(d => { minX = Math.min(minX, d.x); maxX = Math.max(maxX, d.x); });
      s.yOffset = offset - minX;
      offset += (maxX - minX) + GAP;
    });
  }

  function docGlyph(sel) {
    sel.append('path').attr('d', 'M-3.2,-5 H1.4 L3.4,-3 V5 H-3.2 Z').attr('fill', '#fff');
    sel.append('path').attr('d', 'M1.4,-5 V-3 H3.4').attr('fill', 'none').attr('stroke', colorOf).attr('stroke-width', 0.9);
    sel.append('path').attr('d', 'M-1.6,-0.6 H1.6 M-1.6,1.8 H1.6').attr('stroke', colorOf).attr('stroke-width', 0.9).attr('stroke-linecap', 'round');
  }

  function renderTree(s, src) {
    const t = svg.transition().duration(320);
    const nodes = s.root.descendants().reverse();
    const links = s.root.links();

    const node = s.gNode.selectAll('g.node').data(nodes, d => d.id);
    const nodeEnter = node.enter().append('g').attr('class', 'node')
      .attr('transform', 'translate(' + src.y0 + ',' + src.x0 + ')')
      .attr('fill-opacity', 0).attr('stroke-opacity', 0)
      .on('click', (e, d) => {
        const hasKids = d.children || d._children;
        if (!hasKids) { openDoc(d); return; }
        d.children = d.children ? null : d._children; refresh(d);
      });

    const W = d => nodeW(d.data.name, d.depth === 0);

    nodeEnter.append('rect')
      .attr('height', d => d.depth === 0 ? 32 : 28).attr('y', d => d.depth === 0 ? -16 : -14)
      .attr('rx', 13).attr('ry', 13)
      .attr('x', d => -W(d) / 2).attr('width', W)
      .attr('fill', 'var(--card)').attr('stroke', colorOf).attr('stroke-width', d => d.depth === 0 ? 2.4 : 1.6);

    nodeEnter.append('circle').attr('r', 4).attr('cx', d => -W(d) / 2).attr('fill', colorOf);

    nodeEnter.append('text').attr('class', d => 'label' + (d.depth === 0 ? ' root' : ''))
      .attr('text-anchor', 'start').attr('dy', '0.32em')
      .attr('x', d => -W(d) / 2 + 14)
      .text(d => fitText(d.data.name, d.depth === 0))
      .append('title').text(d => d.data.name);

    // doc icon (always) — open the wiki doc
    const doc = nodeEnter.append('g').attr('class', 'docbtn')
      .attr('transform', d => 'translate(' + (W(d) / 2 - 2) + ',0)')
      .on('click', (e, d) => { e.stopPropagation(); openDoc(d); });
    doc.append('title').text('Open doc');
    doc.append('circle').attr('r', 9).attr('fill', colorOf);
    doc.each(function () { docGlyph(d3.select(this)); });

    // count badge (collapsed) — outside right
    const badge = nodeEnter.append('g').attr('class', 'badge')
      .attr('transform', d => 'translate(' + (W(d) / 2 + 20) + ',0)');
    badge.append('circle').attr('r', 9).attr('fill', colorOf);
    badge.append('text').attr('class', 'count').attr('text-anchor', 'middle').attr('dy', '0.32em');

    // add button (hover, server mode) — below the doc icon
    const add = nodeEnter.append('g').attr('class', 'addbtn')
      .attr('transform', d => 'translate(' + (W(d) / 2 - 2) + ',20)')
      .on('click', (e, d) => { e.stopPropagation(); openAddModal(d); });
    add.append('title').text('Add note here');
    add.append('circle').attr('r', 9).attr('fill', colorOf);
    add.append('path').attr('d', 'M0,-4 V4 M-4,0 H4').attr('stroke', '#fff').attr('stroke-width', 2).attr('stroke-linecap', 'round');

    const merged = node.merge(nodeEnter);
    merged.select('.badge').style('display', d => collapsed(d) ? null : 'none');
    merged.select('.badge .count').text(d => collapsed(d) ? d._children.length : '');
    merged.transition(t)
      .attr('transform', d => 'translate(' + d.y + ',' + d.x + ')')
      .attr('fill-opacity', 1).attr('stroke-opacity', 1);

    node.exit().transition(t).remove()
      .attr('transform', 'translate(' + src.y + ',' + src.x + ')')
      .attr('fill-opacity', 0).attr('stroke-opacity', 0);

    const link = s.gLink.selectAll('path').data(links, d => d.target.id);
    const linkEnter = link.enter().append('path').attr('class', 'link')
      .attr('stroke', d => colorOf(d.target))
      .attr('d', () => { const o = { x: src.x0, y: src.y0 }; return diagonal({ source: o, target: o }); });
    link.merge(linkEnter).transition(t).attr('d', diagonal).attr('stroke', d => colorOf(d.target));
    link.exit().transition(t).remove()
      .attr('d', () => { const o = { x: src.x, y: src.y }; return diagonal({ source: o, target: o }); });

    s.root.eachBefore(d => { d.x0 = d.x; d.y0 = d.y; });
  }

  function refresh(source) {
    layout();
    states.forEach(s => {
      const src = (source && source.ti === s.ti) ? source : s.root;
      s.g.transition().duration(320).attr('transform', 'translate(' + MARGIN_L + ',' + s.yOffset + ')');
      renderTree(s, src);
    });
  }

  function fit() {
    layout();
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    states.forEach(s => s.root.each(d => {
      const X = MARGIN_L + d.y, Y = s.yOffset + d.x;
      minX = Math.min(minX, X); maxX = Math.max(maxX, X);
      minY = Math.min(minY, Y); maxY = Math.max(maxY, Y);
    }));
    const w = window.innerWidth, h = window.innerHeight;
    const tw = (maxX - minX) + 420, th = (maxY - minY) + 160;
    const k = Math.min(1.4, Math.min(w / tw, h / th));
    const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2;
    svg.transition().duration(440).call(zoom.transform,
      d3.zoomIdentity.translate(w / 2 - k * cx, h / 2 - k * cy).scale(k));
  }

  function openDoc(d) {
    const rel = repoRel(d.data.url);
    if (SERVER) fetch('/api/open?path=' + encodeURIComponent(rel)).catch(() => {});
    else if (d.data.url) window.open(d.data.url, '_blank');
  }

  // ---- add-note modal ----
  let addParent = null; // d3 node, or null = root
  function openAddModal(d) {
    addParent = d;
    const ctx = d ? ('Adds a note under “' + d.data.name + '”') : 'Adds a new top-level pursuit';
    document.getElementById('modal-ctx').textContent = ctx;
    document.getElementById('note-title').value = '';
    document.getElementById('note-body').value = '';
    document.getElementById('note-msg').textContent = SERVER ? '' : 'Run via: node dashboard/serve.js — file mode can\'t write.';
    document.getElementById('modal').hidden = false;
    document.getElementById('note-title').focus();
  }
  function closeModal() { document.getElementById('modal').hidden = true; }
  async function submitAdd() {
    const title = document.getElementById('note-title').value.trim();
    const note = document.getElementById('note-body').value;
    const msg = document.getElementById('note-msg');
    if (!title) { msg.textContent = 'Title required.'; return; }
    if (!SERVER) { msg.textContent = 'Server not running — start: node dashboard/serve.js'; return; }
    msg.textContent = 'Adding…';
    try {
      const parent = addParent ? repoRel(addParent.data.url) : 'root';
      const r = await fetch('/api/add', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parent, title, note }) });
      const j = await r.json();
      if (!j.ok) { msg.textContent = 'Error: ' + j.error; return; }
      window.TREES = j.trees;
      buildStates(window.TREES);
      refresh(null); setTimeout(fit, 360);
      closeModal();
    } catch (e) { msg.textContent = 'Error: ' + e.message; }
  }

  d3.select('#expand').on('click', () => { states.forEach(s => s.root.each(d => { if (d._children) d.children = d._children; })); refresh(null); setTimeout(fit, 360); });
  d3.select('#collapse').on('click', () => { states.forEach(s => s.root.descendants().forEach(d => { if (d.depth >= 1 && d.children) { d._children = d.children; d.children = null; } })); refresh(null); setTimeout(fit, 360); });
  d3.select('#fit').on('click', fit);
  d3.select('#addnote').on('click', () => openAddModal(null));
  document.getElementById('note-cancel').onclick = closeModal;
  document.getElementById('note-save').onclick = submitAdd;
  document.getElementById('modal').addEventListener('click', e => { if (e.target.id === 'modal') closeModal(); });
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });
  window.addEventListener('resize', fit);

  // detect server mode, then render
  fetch('/api/ping').then(r => r.ok).then(ok => { SERVER = !!ok; }).catch(() => { SERVER = false; })
    .finally(() => { document.body.classList.toggle('server', SERVER); });
  buildStates(window.TREES);
  refresh(null);
  setTimeout(fit, 60);
})();
