window.MAPS = {
  "order": [
    "orders-operations",
    "screenery-flow",
    "illustrator",
    "layers",
    "finalizing-file",
    "file"
  ],
  "maps": {
    "orders-operations": {
      "slug": "orders-operations",
      "id": "m-ords01",
      "title": "Orders Operations",
      "kind": "process",
      "url": "../maps-data/orders-operations/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "screenery-flow": {
      "slug": "screenery-flow",
      "id": "m-scrn01",
      "title": "Screenery — Operating Flow",
      "kind": "process",
      "url": "../maps-data/screenery-flow/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "illustrator": {
      "slug": "illustrator",
      "id": "ill001",
      "title": "Illustrator",
      "kind": "process",
      "url": "../maps-data/illustrator/index.md",
      "nodes": [
        {
          "id": "ntppap",
          "slug": "finalizing-file",
          "name": "FINALIZING File",
          "type": "subprocess-link",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 443,
          "y": 755,
          "lane": null,
          "link_map": "finalizing-file",
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/illustrator/finalizing-file.md"
        },
        {
          "id": "nscn2g",
          "slug": "file",
          "name": "FILE",
          "type": "subprocess-link",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 347,
          "y": 539,
          "lane": null,
          "link_map": "file",
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/illustrator/file.md"
        }
      ],
      "edges": [],
      "frames": []
    },
    "layers": {
      "slug": "layers",
      "id": "lay001",
      "title": "Layers",
      "kind": "process",
      "url": "../maps-data/layers/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "finalizing-file": {
      "slug": "finalizing-file",
      "id": "m79v9v",
      "title": "Finalizing File",
      "kind": "process",
      "url": "../maps-data/finalizing-file/index.md",
      "nodes": [
        {
          "id": "ntdz88",
          "slug": "overlapping-paths",
          "name": "OVERLAPPING paths",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 442,
          "y": 490,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/overlapping-paths.md"
        },
        {
          "id": "nd3vvb",
          "slug": "spot-color",
          "name": "SPOT color",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 753,
          "y": 490,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": 8,
          "url": "../maps-data/finalizing-file/spot-color.md"
        },
        {
          "id": "nm1gft",
          "slug": "collection",
          "name": "COLLECTION",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1025,
          "y": 491,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/collection.md"
        },
        {
          "id": "n9gf95",
          "slug": "checking",
          "name": "CHECKING",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1327,
          "y": 494,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/checking.md"
        },
        {
          "id": "nj6q05",
          "slug": "split-files",
          "name": "SPLIT files",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1590,
          "y": 491,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/split-files.md"
        },
        {
          "id": "nv6860",
          "slug": "preflight",
          "name": "PREFLIGHT",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 201,
          "y": 382,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/preflight.md"
        }
      ],
      "edges": [
        {
          "from": "ntdz88",
          "to": "nd3vvb",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nd3vvb",
          "to": "nm1gft",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nm1gft",
          "to": "n9gf95",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "n9gf95",
          "to": "nj6q05",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nv6860",
          "to": "ntdz88",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        }
      ],
      "frames": []
    },
    "file": {
      "slug": "file",
      "id": "mbuq47",
      "title": "FILE",
      "kind": "process",
      "url": "../maps-data/file/index.md",
      "nodes": [
        {
          "id": "n842k9",
          "slug": "front-layer",
          "name": "FRONT layer",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 492,
          "y": 574,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": 8,
          "url": "../maps-data/file/front-layer.md"
        },
        {
          "id": "n2taty",
          "slug": "middle-layer",
          "name": "MIDDLE LAYER",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 494,
          "y": 652,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": 5,
          "url": "../maps-data/file/middle-layer.md"
        },
        {
          "id": "nxrxjx",
          "slug": "back-layer",
          "name": "BACK LAYER",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 486,
          "y": 730,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": 7,
          "url": "../maps-data/file/back-layer.md"
        },
        {
          "id": "nk018k",
          "slug": "objects",
          "name": "OBJECTS",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 287,
          "y": 602,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/objects.md"
        },
        {
          "id": "n6g2wa",
          "slug": "slots",
          "name": "SLOTS",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 977,
          "y": 880,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/slots.md"
        },
        {
          "id": "n69mdp",
          "slug": "flaps-sockets",
          "name": "FLAPS & SOCKETS",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 970,
          "y": 960,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/flaps-sockets.md"
        },
        {
          "id": "nwb4nc",
          "slug": "stabilizers",
          "name": "STABILIZERS",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 387,
          "y": 1010,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/stabilizers.md"
        },
        {
          "id": "nyzxrq",
          "slug": "naming",
          "name": "NAMING",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 285,
          "y": 502,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/naming.md"
        },
        {
          "id": "nn5tcr",
          "slug": "panels",
          "name": "PANELS",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 392,
          "y": 929,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/file/panels.md"
        }
      ],
      "edges": [],
      "frames": []
    }
  },
  "issues": []
};
