window.MAPS = {
  "order": [
    "orders-operations",
    "screenery-flow",
    "illustrator",
    "layers",
    "finalizing-file"
  ],
  "maps": {
    "orders-operations": {
      "slug": "orders-operations",
      "id": "m-ords01",
      "title": "Orders Operations",
      "kind": "process",
      "url": "../maps-data/orders-operations/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "screenery-flow": {
      "slug": "screenery-flow",
      "id": "m-scrn01",
      "title": "Screenery — Operating Flow",
      "kind": "process",
      "url": "../maps-data/screenery-flow/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "illustrator": {
      "slug": "illustrator",
      "id": "ill001",
      "title": "Illustrator",
      "kind": "process",
      "url": "../maps-data/illustrator/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "layers": {
      "slug": "layers",
      "id": "lay001",
      "title": "Layers",
      "kind": "process",
      "url": "../maps-data/layers/index.md",
      "nodes": [],
      "edges": [],
      "frames": []
    },
    "finalizing-file": {
      "slug": "finalizing-file",
      "id": "m79v9v",
      "title": "Finalizing File",
      "kind": "process",
      "url": "../maps-data/finalizing-file/index.md",
      "nodes": [
        {
          "id": "ntdz88",
          "slug": "overlapping-paths",
          "name": "OVERLAPPING paths",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 442,
          "y": 490,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/overlapping-paths.md"
        },
        {
          "id": "nd3vvb",
          "slug": "spot-color",
          "name": "SPOT color",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 753,
          "y": 490,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": 8,
          "url": "../maps-data/finalizing-file/spot-color.md"
        },
        {
          "id": "nm1gft",
          "slug": "registration-marks",
          "name": "REGISTRATION marks",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1025,
          "y": 491,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/registration-marks.md"
        },
        {
          "id": "n9gf95",
          "slug": "checking",
          "name": "CHECKING",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1327,
          "y": 494,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/checking.md"
        },
        {
          "id": "nj6q05",
          "slug": "split-files",
          "name": "SPLIT files",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 1590,
          "y": 491,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/split-files.md"
        },
        {
          "id": "nv6860",
          "slug": "preflight",
          "name": "PREFLIGHT",
          "type": "step",
          "summary": null,
          "icon": null,
          "tags": [],
          "status": null,
          "refs": [],
          "refsCollapsed": false,
          "x": 201,
          "y": 382,
          "lane": null,
          "link_map": null,
          "gate": null,
          "scale": 1,
          "hl": false,
          "color": null,
          "url": "../maps-data/finalizing-file/preflight.md"
        }
      ],
      "edges": [
        {
          "from": "ntdz88",
          "to": "nd3vvb",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nd3vvb",
          "to": "nm1gft",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nm1gft",
          "to": "n9gf95",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "n9gf95",
          "to": "nj6q05",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        },
        {
          "from": "nv6860",
          "to": "ntdz88",
          "label": "",
          "bend": 0,
          "color": null,
          "route": "bezier"
        }
      ],
      "frames": []
    }
  },
  "issues": []
};
