#!/usr/bin/env python3
"""pursuit_rollup — make the pursuit forest correspond to wiki sections.

Scans wiki content pages for a `pursuit:` frontmatter field, groups them by
pursuit slug, and injects a sentinel-bounded "wiki pages in this pursuit"
rollup into each pursuit node page under `pursuits/`. The pursuit node thus
becomes the landing page for its wiki section.

- Idempotent: re-running with no content change rewrites nothing.
- `--check`: exit 1 if any rollup is stale (CI / lint use), no writes.

Pure stdlib. Skips the same trees as token_economy/wiki.py.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SKIP_PARTS = {".git", ".token-economy", "__pycache__", ".pytest_cache",
              "vendor", ".claude", "node_modules"}
# First-level dirs that are tooling/templates, not wiki content. A `pursuit:`
# line there (e.g. the literal {{pursuit}} in a template) is not a real tag.
# Mirrors token_economy/wiki.py's frontmatter-exempt set + code/build dirs.
NON_CONTENT = {"templates", "skills", "prompts", "hooks", "configs",
               "extensions", "adapters", "tools", "token_economy",
               "dashboard", "tests", "bench", "eval"}
START = "<!-- pursuit-rollup:start -->"
END = "<!-- pursuit-rollup:end -->"
FM_RE = re.compile(r"^﻿?---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)


def parse_fm(text: str) -> dict[str, str]:
    m = FM_RE.match(text)
    if not m:
        return {}
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line or line[:1] in (" ", "\t", "-"):
            continue
        k, _, v = line.partition(":")
        fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm


def title_of(text: str, path: Path) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").replace("_", " ").title()


def page_link(root: Path, path: Path) -> str:
    rel = path.relative_to(root).as_posix()
    return rel[:-3] if rel.endswith(".md") else rel


def node_slug(root: Path, node: Path) -> str:
    """Slug for a pursuit node: dir name for an index.md, else the file stem.
    The root pursuits/index.md is the forest root ('_root')."""
    rel = node.relative_to(root / "pursuits")
    if node.name == "index.md":
        return "_root" if rel.parent == Path(".") else rel.parent.name
    return node.stem


def collect(root: Path):
    """Return (nodes: slug->Path, members: slug->list[(title, link)])."""
    pursuits_dir = root / "pursuits"
    nodes: dict[str, Path] = {}
    if pursuits_dir.is_dir():
        for p in sorted(pursuits_dir.rglob("*.md")):
            nodes[node_slug(root, p)] = p

    members: dict[str, list[tuple[str, str]]] = {}
    for p in sorted(root.rglob("*.md")):
        parts = p.relative_to(root).parts
        if any(x in SKIP_PARTS for x in parts):
            continue
        if parts and (parts[0] == "pursuits" or parts[0] in NON_CONTENT):
            continue  # nodes don't roll up into themselves; tooling isn't content
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        fm = parse_fm(text)
        slug = fm.get("pursuit", "").strip()
        if not slug or slug.lower() == "none":
            continue
        members.setdefault(slug, []).append((title_of(text, p), page_link(root, p)))
    return nodes, members


def render_block(slug: str, items: list[tuple[str, str]], counts: dict[str, int] | None) -> str:
    lines = [START,
             "## Wiki pages in this pursuit",
             "_Auto-generated by `./te wiki rollup` — do not hand-edit between sentinels._",
             ""]
    if counts is not None:  # forest root: per-pursuit counts
        if counts:
            for s in sorted(counts):
                lines.append(f"- **{s}** — {counts[s]} page(s)")
        else:
            lines.append("_No pursuit-tagged wiki pages yet._")
    elif items:
        for title, link in sorted(items, key=lambda t: t[0].lower()):
            lines.append(f"- [[{link}]] — {title}")
    else:
        lines.append("_No wiki pages tagged to this pursuit yet. Tag a page with `pursuit: " + slug + "`._")
    lines.append(END)
    return "\n".join(lines)


def inject(text: str, block: str) -> str:
    if START in text and END in text:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.DOTALL)
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + "\n" + block + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="inject pursuit→pages rollups into pursuit node pages")
    ap.add_argument("--root", default=".", help="wiki root (repo root)")
    ap.add_argument("--check", action="store_true", help="exit 1 if any rollup is stale; no writes")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve()
    if not (root / "pursuits").is_dir():
        print(f"error: no pursuits/ under {root}", file=sys.stderr)
        return 2

    nodes, members = collect(root)
    counts = {s: len(v) for s, v in members.items()}
    stale, written = [], []
    for slug, node in sorted(nodes.items()):
        block = render_block(slug, members.get(slug, []),
                             counts if slug == "_root" else None)
        old = node.read_text(encoding="utf-8", errors="ignore")
        new = inject(old, block)
        if new != old:
            stale.append(node.relative_to(root).as_posix())
            if not args.check:
                node.write_text(new, encoding="utf-8")
                written.append(node.relative_to(root).as_posix())

    # report unknown pursuit slugs (tagged but no matching node) — surfaces typos
    orphan_slugs = sorted(set(members) - set(nodes))

    if args.check:
        if stale:
            print("STALE rollups:")
            for s in stale:
                print("  " + s)
        if orphan_slugs:
            print("WARN unknown pursuit slugs (no node): " + ", ".join(orphan_slugs))
        print(f"nodes={len(nodes)} tagged_pages={sum(counts.values())} stale={len(stale)}")
        return 1 if stale else 0

    print(f"nodes={len(nodes)} tagged_pages={sum(counts.values())} written={len(written)}")
    for w in written:
        print("  updated " + w)
    if orphan_slugs:
        print("WARN unknown pursuit slugs (no node): " + ", ".join(orphan_slugs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
